version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ checksum "package.json" }}
      - run: npm test
      - run: npm run build
